# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='webpage',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
