# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0002_auto_20170216_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='abbriviation',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
