# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0003_auto_20170228_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='place',
            field=models.CharField(default='Trondheim', max_length=40),
            preserve_default=False,
        ),
    ]
