# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 15:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20170309_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questions.Course'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.TimeField(default=datetime.datetime(2017, 3, 9, 16, 38, 27, 668832)),
        ),
    ]
