# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 15:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20170309_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='students',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.TimeField(default=datetime.datetime(2017, 3, 9, 16, 44, 32, 984822)),
        ),
    ]
