# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 15:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20170309_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.TimeField(default=datetime.datetime(2017, 3, 9, 16, 49, 48, 949161)),
        ),
    ]
