# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 10:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20170309_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='examDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.TimeField(default=datetime.datetime(2017, 3, 24, 11, 36, 14, 896492)),
        ),
    ]
