# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 11:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20170324_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 12, 51, 21, 929423)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.TimeField(default=datetime.datetime(2017, 3, 24, 12, 51, 21, 931426)),
        ),
    ]
