# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 11:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20170324_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.Course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.TimeField(default=datetime.datetime(2017, 3, 24, 12, 54, 23, 121557)),
        ),
        migrations.AlterField(
            model_name='question',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 12, 54, 23, 120556)),
        ),
    ]
