# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 21:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20170405_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 5, 23, 18, 57, 694833)),
        ),
        migrations.AlterField(
            model_name='question',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 5, 23, 18, 57, 694332)),
        ),
    ]
