# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 21:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_auto_20170405_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='question',
            name='anonymous',
        ),
        migrations.AlterField(
            model_name='answer',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 5, 23, 24, 40, 145224)),
        ),
        migrations.AlterField(
            model_name='question',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 5, 23, 24, 40, 144723)),
        ),
    ]
