# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 00:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_auto_20170405_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='answer',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 2, 25, 59, 716756)),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='question',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 2, 25, 59, 716255)),
        ),
    ]
