# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hexcolour',
            field=models.CharField(default='#1b6d85', max_length=7),
        ),
    ]
